# Étape 1 : Builder l’application
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src

# Utiliser le goal 'spring-boot:repackage' pour inclure toutes les dépendances
RUN mvn clean package spring-boot:repackage -DskipTests


# Étape 2 : Image finale légère
FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/order-service-*.jar order-service.jar

# Expose le port (même que dans application.properties)
EXPOSE 8083

# Commande de démarrage
ENTRYPOINT ["java", "-jar", "order-service.jar"]
